#!/bin/bash

set -eo pipefail

ABBREV='<ABBREV>'
REGULAR_USER='<REGULAR_USER>'

T_BEGIN=$(date +'%s')

echo '--------------------'
echo 'ls -l /usr/local/bin'
ls -l /usr/local/bin

# Prepare apt-get
/usr/local/bin/aptget

# Set environment variables to cut down on annoying warning messages
export DEBIAN_FRONTEND='noninteractive'
export DEBCONF_NOWARNINGS='true'
export HOME=/root
export LC_ALL=C

echo '##########################'
echo "BEGIN $ABBREV-root actions"
echo '##########################'

echo "/usr/local/bin/check-$ABBREV" >> /usr/local/bin/check

wait
echo '--------------------------------------------'
echo 'BEGIN: installing UTF-8 (needed for Ansible)'
echo '--------------------------------------------'
wait

# Sources:
# https://serverfault.com/questions/54591/how-to-install-change-locale-on-debian
# https://www.graalvm.org/latest/reference-manual/ruby/UTF8Locale/
wait
sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen
wait
locale-gen
export LANG='en_US.UTF-8'
export LANGUAGE='en_US.UTF-8'
export LC_ALL='en_US.UTF-8'
wait
echo ''
echo '------'
echo 'locale'
locale
echo ''
echo '-----------------------------------------------'
echo 'FINISHED: installing UTF-8 (needed for Ansible)'
echo '-----------------------------------------------'
wait

# Install Ansible
echo '---------------------------------'
echo 'BEGIN: apt-get install -y ansible'
echo '---------------------------------'
apt-get install -y ansible
echo '------------------------------------'
echo 'FINISHED: apt-get install -y ansible'
echo '------------------------------------'

echo '#############################'
echo "FINISHED $ABBREV-root actions"
echo '#############################'

su -c /usr/local/bin/$ABBREV-user $REGULAR_USER
/usr/local/bin/finalize-root
su -c /usr/local/bin/finalize-user $REGULAR_USER
su -c /usr/local/bin/check $REGULAR_USER

T_FINISH=$(date +'%s')
T_ELAPSED=$(($T_FINISH-$T_BEGIN))
echo '--------------------------------'
echo 'Time to modify the Docker image:'
echo "$(($T_ELAPSED / 60)) minutes and $(($T_ELAPSED % 60)) seconds"
