name: Build-min_stage1

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        MATRIX_CODE_NAME: ['bookworm']

    # The name of the Docker image to be pushed must be set here.
    # Relying on the tmp/bin/set-variables script caused the wrong images
    # to be pushed during certain builds.
    env:
      CODE_NAME_CI: ${{ matrix.MATRIX_CODE_NAME }}
      ABBREV_CI: min-ansible

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: bash $ABBREV_CI-$CODE_NAME_CI.sh
